INSERT INTO user_roles (id, name) VALUES (1, 'ROLE_ADMIN')
ON CONFLICT (id) DO UPDATE
SET name = 'ROLE_ADMIN';
INSERT INTO user_roles (id, name) VALUES (2, 'ROLE_USER')
ON CONFLICT (id) DO UPDATE
SET name = 'ROLE_USER';